name: carnet_digital_istlt
description: "Aplicación de carnet digital para el ISTLT"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^1.1.0
  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  
  
  assets:
    - assets/logo_ISTL_02.png
    - assets/logo_ISTL_10.png
    - assets/logo_ISTL_08.png
